version: '2'

services:
  app:
    build: app/.
    ports:
      - "8081:8080"
    depends_on:
      - mongodb
  mongodb:
    build: mongo/.
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data:/data/db