version: '2'

services:
  app:
    build: app/.
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  sonar:
    build: sonar/.
    ports:
      - "9000:9000"
      - "9092:9092"