version: '2'

services:
  jenkins:
    build: jenkins/.
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - ./jenkins/data:/var/jenkins_home
    depends_on:
      - sonar
  sonar:
    build: sonar/.
    ports:
      - "9000:9000"
      - "9092:9092"